language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t xdimitarx/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true xdimitarx/react-test npm test

after_success:
  - docker build -t xdimitarx/multi-client ./client
  - docker build -t xdimitarx/multi-nginx ./nginx
  - docker build -t xdimitarx/multi-server ./server
  - docker build -t xdimitarx/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push xdimitarx/multi-client
  - docker push xdimitarx/multi-nginx
  - docker push xdimitarx/multi-server
  - docker push xdimitarx/multi-worker